targets:rpi4: implement multistrap packaging
sartura/replica pull request #25
Opened 2021-12-08 14:35 UTC by jela1337

This change adds the option to build a fully custom rpi4 debian image based on multistrap.

This implementation is still experimental, and does not guarantee a working system.

Signed-off-by: Alen Jelavic <alen.jelavic@sartura.hr>

2021-12-09 15:38 UTC, jpetrina requested changes

2021-12-09 15:38 UTC, jpetrina commented on targets/rpi4.docker
> +setdef(`__debootstrap_dinclude__', `gpg,dirmngr,debian-keyring,fancontrol,firmware-brcm80211,ca-certificates,multistrap')dnl
I think we can remove `firmware-brcm80211` and perhaps even `__debootstrap_dinclude__` and `DEBOOTSTRAP_INCLUDE`.

2021-12-09 15:38 UTC, jpetrina commented on targets/rpi4.docker
> +    mkdir /home/debian && \
I would avoid touching anything in `/` much, can we move this to `/tmp` or `/var` and back? If we need a small Debian installation to run `multistrap` from, perhaps we could simply `deboostrap` in `/var/cache` and not move anything afterwards.

2021-12-09 15:38 UTC, jpetrina commented on repos/debian/rpi4/config/multistrap.conf
> +packages=docker-ce docker-ce-cli containerd.io
We shouldn't install this by default. Let's leave these commented out, but we should ensure this works.

2021-12-09 15:40 UTC, jpetrina commented on targets/rpi4.docker
> +ifelse(index(__debootstrap_include__, `1'),0,`dnl
Can we remove this check?

2021-12-23 21:03 UTC, merged

2021-12-23 21:03 UTC, jsmolic approved these changes